[2024-03-07T04:17:02.533+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extraçao_de_dados_do_linkedin.Carregamento_dos_dados_analitico manual__2024-03-07T04:13:53.292653+00:00 [queued]>
[2024-03-07T04:17:02.552+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extraçao_de_dados_do_linkedin.Carregamento_dos_dados_analitico manual__2024-03-07T04:13:53.292653+00:00 [queued]>
[2024-03-07T04:17:02.553+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-03-07T04:17:02.612+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Carregamento_dos_dados_analitico> on 2024-03-07 04:13:53.292653+00:00
[2024-03-07T04:17:02.619+0000] {standard_task_runner.py:60} INFO - Started process 5900 to run task
[2024-03-07T04:17:02.623+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Extraçao_de_dados_do_linkedin', 'Carregamento_dos_dados_analitico', 'manual__2024-03-07T04:13:53.292653+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/dag_exemplo.py', '--cfg-path', '/tmp/tmp83fiipqb']
[2024-03-07T04:17:02.626+0000] {standard_task_runner.py:88} INFO - Job 89: Subtask Carregamento_dos_dados_analitico
[2024-03-07T04:17:02.731+0000] {task_command.py:423} INFO - Running <TaskInstance: Extraçao_de_dados_do_linkedin.Carregamento_dos_dados_analitico manual__2024-03-07T04:13:53.292653+00:00 [running]> on host 4fca1e22de4a
[2024-03-07T04:17:02.891+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extraçao_de_dados_do_linkedin' AIRFLOW_CTX_TASK_ID='Carregamento_dos_dados_analitico' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T04:13:53.292653+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-07T04:13:53.292653+00:00'
[2024-03-07T04:17:04.257+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-03-07T04:17:04.272+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Extraçao_de_dados_do_linkedin, task_id=Carregamento_dos_dados_analitico, execution_date=20240307T041353, start_date=20240307T041702, end_date=20240307T041704
[2024-03-07T04:17:04.362+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-07T04:17:04.384+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
