[2024-03-07T04:16:59.101+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extraçao_de_dados_do_linkedin.Transformaçao_dos_dados manual__2024-03-07T04:13:53.292653+00:00 [queued]>
[2024-03-07T04:16:59.112+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extraçao_de_dados_do_linkedin.Transformaçao_dos_dados manual__2024-03-07T04:13:53.292653+00:00 [queued]>
[2024-03-07T04:16:59.114+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-03-07T04:16:59.251+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Transformaçao_dos_dados> on 2024-03-07 04:13:53.292653+00:00
[2024-03-07T04:16:59.260+0000] {standard_task_runner.py:60} INFO - Started process 5895 to run task
[2024-03-07T04:16:59.263+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Extraçao_de_dados_do_linkedin', 'Transformaçao_dos_dados', 'manual__2024-03-07T04:13:53.292653+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dag_exemplo.py', '--cfg-path', '/tmp/tmp3pn9gyuc']
[2024-03-07T04:16:59.266+0000] {standard_task_runner.py:88} INFO - Job 88: Subtask Transformaçao_dos_dados
[2024-03-07T04:16:59.355+0000] {task_command.py:423} INFO - Running <TaskInstance: Extraçao_de_dados_do_linkedin.Transformaçao_dos_dados manual__2024-03-07T04:13:53.292653+00:00 [running]> on host 4fca1e22de4a
[2024-03-07T04:16:59.512+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extraçao_de_dados_do_linkedin' AIRFLOW_CTX_TASK_ID='Transformaçao_dos_dados' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T04:13:53.292653+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-07T04:13:53.292653+00:00'
[2024-03-07T04:16:59.746+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:74: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_tec.drop_duplicates(inplace=True)

[2024-03-07T04:16:59.749+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:76: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_tec.drop_duplicates(subset=["job_id"], inplace=True)

[2024-03-07T04:16:59.750+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:78: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_tec.applications.fillna("Hidden", inplace=True)

[2024-03-07T04:16:59.775+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:87: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_tec.experience_level.fillna("Assistente", inplace=True)

[2024-03-07T04:16:59.776+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:89: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_tec.job_type.fillna("Tempo integral", inplace=True)

[2024-03-07T04:16:59.778+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:91: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_tec.role.fillna("Engenharia e Tecnologia da informação", inplace=True)

[2024-03-07T04:16:59.779+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:92: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_tec.sectors.fillna(

[2024-03-07T04:16:59.780+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:96: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_tec.description.fillna("Sem descrição", inplace=True)

[2024-03-07T04:16:59.783+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:153: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_nao_nulos["temp"] = (

[2024-03-07T04:16:59.893+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:156: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_nao_nulos["requisitos"] = dados_nao_nulos.temp.apply(

[2024-03-07T04:17:00.024+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:159: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_nao_nulos["lista"] = dados_nao_nulos.temp.apply(

[2024-03-07T04:17:00.086+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-03-07T04:17:00.095+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Extraçao_de_dados_do_linkedin, task_id=Transformaçao_dos_dados, execution_date=20240307T041353, start_date=20240307T041659, end_date=20240307T041700
[2024-03-07T04:17:00.159+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-07T04:17:00.179+0000] {taskinstance.py:3280} INFO - 2 downstream tasks scheduled from follow-on schedule check
