[2024-03-04T20:53:23.563+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extraçao_de_dados_do_linkedin.Transformaçao_dos_dados manual__2024-03-04T20:53:20.390169+00:00 [queued]>
[2024-03-04T20:53:23.572+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extraçao_de_dados_do_linkedin.Transformaçao_dos_dados manual__2024-03-04T20:53:20.390169+00:00 [queued]>
[2024-03-04T20:53:23.573+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-03-04T20:53:23.622+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Transformaçao_dos_dados> on 2024-03-04 20:53:20.390169+00:00
[2024-03-04T20:53:23.661+0000] {standard_task_runner.py:60} INFO - Started process 1176 to run task
[2024-03-04T20:53:23.663+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Extraçao_de_dados_do_linkedin', 'Transformaçao_dos_dados', 'manual__2024-03-04T20:53:20.390169+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/dag_exemplo.py', '--cfg-path', '/tmp/tmpz7n56jej']
[2024-03-04T20:53:23.665+0000] {standard_task_runner.py:88} INFO - Job 38: Subtask Transformaçao_dos_dados
[2024-03-04T20:53:23.742+0000] {task_command.py:423} INFO - Running <TaskInstance: Extraçao_de_dados_do_linkedin.Transformaçao_dos_dados manual__2024-03-04T20:53:20.390169+00:00 [running]> on host 43d6e1a41402
[2024-03-04T20:53:24.044+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extraçao_de_dados_do_linkedin' AIRFLOW_CTX_TASK_ID='Transformaçao_dos_dados' AIRFLOW_CTX_EXECUTION_DATE='2024-03-04T20:53:20.390169+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-04T20:53:20.390169+00:00'
[2024-03-04T20:53:24.082+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:60: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_tec.drop_duplicates(inplace=True)

[2024-03-04T20:53:24.086+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:62: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_tec.drop_duplicates(subset=["job_id"], inplace=True)

[2024-03-04T20:53:24.087+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:64: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_tec.applications.fillna("Hidden", inplace=True)

[2024-03-04T20:53:24.089+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:73: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_tec.experience_level.fillna("Assistente", inplace=True)

[2024-03-04T20:53:24.091+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:75: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_tec.job_type.fillna("Tempo integral", inplace=True)

[2024-03-04T20:53:24.092+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:77: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_tec.role.fillna("Engenharia e Tecnologia da informação", inplace=True)

[2024-03-04T20:53:24.093+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:78: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_tec.sectors.fillna(

[2024-03-04T20:53:24.095+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:82: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_tec.description.fillna("Sem descrição", inplace=True)

[2024-03-04T20:53:24.098+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:139: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_nao_nulos["temp"] = (

[2024-03-04T20:53:24.694+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:142: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_nao_nulos["requisitos"] = dados_nao_nulos.temp.apply(

[2024-03-04T20:53:25.305+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_exemplo.py:145: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_nao_nulos["lista"] = dados_nao_nulos.temp.apply(

[2024-03-04T20:53:25.610+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-03-04T20:53:25.619+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Extraçao_de_dados_do_linkedin, task_id=Transformaçao_dos_dados, execution_date=20240304T205320, start_date=20240304T205323, end_date=20240304T205325
[2024-03-04T20:53:25.763+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-04T20:53:25.780+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
